// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDm9xxiuj5yhetcvyDkjD54YRd_SUmf8aY',
//     appId: '1:521195206251:web:775feb28048bd77b47632e',
//     messagingSenderId: '521195206251',
//     projectId: 'flutter07-1ac78',
//     authDomain: 'flutter07-1ac78.firebaseapp.com',
//     storageBucket: 'flutter07-1ac78.firebasestorage.app',
//     measurementId: 'G-0L35KXCP5F',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDm9xxiuj5yhetcvyDkjD54YRd_SUmf8aY',
//     appId: '1:521195206251:android:d747944fba8de23d47632e',
//     messagingSenderId: '521195206251',
//     projectId: 'flutter07-1ac78',
//     storageBucket: 'flutter07-1ac78.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDm9xxiuj5yhetcvyDkjD54YRd_SUmf8aY',
//     appId: '1:521195206251:android:d747944fba8de23d47632e',
//     messagingSenderId: '521195206251',
//     projectId: 'flutter07-1ac78',
//     storageBucket: 'flutter07-1ac78.firebasestorage.app',
//     iosClientId:
//         '521195206251-xxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com',
//     iosBundleId: 'com.example.dailyJournalApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDm9xxiuj5yhetcvyDkjD54YRd_SUmf8aY',
//     appId: '1:521195206251:android:d747944fba8de23d47632e',
//     messagingSenderId: '521195206251',
//     projectId: 'flutter07-1ac78',
//     storageBucket: 'flutter07-1ac78.firebasestorage.app',
//     iosClientId:
//         '521195206251-xxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com',
//     iosBundleId: 'com.example.dailyJournalApp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDm9xxiuj5yhetcvyDkjD54YRd_SUmf8aY',
//     appId: '1:521195206251:android:d747944fba8de23d47632e',
//     messagingSenderId: '521195206251',
//     projectId: 'flutter07-1ac78',
//     storageBucket: 'flutter07-1ac78.firebasestorage.app',
//   );
// }

// File: lib/firebase_options.dart
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for the app across platforms.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'FirebaseOptions have not been configured for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDrPk99o6P3Mpw0zbg-Hz49N7E3gYfx05M",
    authDomain: "dailyjournalapp-67779.firebaseapp.com",
    projectId: "dailyjournalapp-67779",
    storageBucket: "dailyjournalapp-67779.appspot.com",
    messagingSenderId: "128647999250",
    appId: "1:128647999250:web:0fb19b325fa13865ce8dcb",
  );
}
